//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Answer
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> PaperId { get; set; }
        public Nullable<int> AttempterId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string CorrectAnswer { get; set; }
        public string AttemptedAnswer { get; set; }
        public Nullable<System.DateTime> AttemptDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Paper Paper { get; set; }
        public virtual Question Question { get; set; }
    }
}
