//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }

        [Key]
        public int Id { get; set; }

        public int PaperId { get; set; }

        [Required(ErrorMessage = "Question text is Required"), DisplayName("Question")]
        public string QuestionText { get; set; }

        [Required(ErrorMessage = "All Options are Required")]
        public string OptionA { get; set; }

        [Required(ErrorMessage = "All Options are Required")]
        public string OptionB { get; set; }
        [Required(ErrorMessage = "All Options are Required")]
        public string OptionC { get; set; }
        [Required(ErrorMessage = "All Options are Required")]
        public string OptionD { get; set; }
        [Required(ErrorMessage = "Correct answer is Required")]
        public string CorrectAnswer { get; set; }

        public virtual Paper Paper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
